# Runs on EACH commit, makes sure that formatting and stuff is correct
# Tests are run on CI, so we don't need to run them here

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake
        language: python
        "types": [python]
        require_serial: true
        args:
          - "--in-place"
          - "--expand-star-imports"
          - "--remove-duplicate-keys"
          - "--remove-unused-variables"
  - repo: local
    hooks:
      - id: black # run on all files (passes some twice, but that's fine)
        name: black
        files: .*.py
        language: system
        entry: pdm run black .
        types: [python]

      - id: mypy
        name: mypy
        language: system # run on src and tests
        entry: pdm run mypy
        files: ^src/.*\.py$|^tests/.*\.py$|pipeline.py
        types: [python]
        args:
          [--ignore-missing-imports, --install-types, --explicit-package-bases]
